rewrite in bash, use pastebin.com instead of rafb.net

diff --git a/nopaste b/nopaste
--- a/nopaste
+++ b/nopaste
@@ -1,159 +1,235 @@
-#!/usr/bin/ruby -w
+#!/bin/bash
 #
-# nopaste -- quick script in the spirit of eatpaste, to generate nopaste urls.
-# See http://www.rafb.net/paste/ for more information.
+# nopaste -- paste to pastebin.com
 #
-# Copyright 2005,2007 Aron Griffis <agriffis n01se.net>
+# Copyright 2005,2007,2009 Aron Griffis <agriffis n01se.net>
 # Released under the GNU General Public License v2
 #
 
-require 'cgi'
-require 'net/http'
-require 'optparse'
-require 'ostruct'
-require 'uri'
+nopaste_version=2.0
+pastebin_url=${PASTEBIN_URL:-http://pastebin.com/pastebin.php}
 
-class CmdLine
-  def self.parse(args)
-    options = OpenStruct.new
-    options.lang = 'Plain Text'
+main() {
+    declare opt_nick=${PASTEBIN_USER:-${USER:-$(whoami)}}
+    declare opt_language=text
+    declare opt_diff=false
+    declare opt_download=false
+    declare opt_xcut=false
+    declare opt_parent=
+    declare expire=f # set by opt_expire()
+    declare shortopts=( n:nick l:language x:xcut p:parent e:expire )
+    declare -a parsed_opts parsed_params
+    parse_cmdline "$@" || exit
+    set -- "${parsed_params[@]}"
 
-    opts = OptionParser.new do |opts|
-      opts.banner = "Usage: nopaste [options]"
-      opts.separator ""
-      opts.separator "Options:"
+    declare -a urls
 
-      opts.on("-l", "--language LANG", 
-              "set language (defaults to \"Plain Text\")") do |x|
-        options.lang = x
-      end
-
-      opts.on("-d", "--description DESCRIPTION", 
-              "set description (defaults to \"stdin\" or filename)") do |x|
-        options.desc = x
-      end
-
-      opts.on("-n", "--nick NICK", 
-              "set nick (defaults to your username)") do |x|
-        options.nick = x
-      end
-
-      opts.on("-t", "--txturl",
-              "return url for the plain text file") do
-        options.txturl = true
-      end
-
-      opts.on("-x", "--xcut", 
-              "nopaste from X selection (using xclip or xcut)") do
-        options.xcut = true 
-      end
-
-      opts.on("--debug",
-              "enable debug output") do
-        options.debug = true
-      end
-
-      opts.on_tail("--help", "show this help") do
-        puts opts
-        exit 
-      end
-
-      opts.on_tail("--version", "show version information") do 
-        puts "nopaste " + $version
-        exit
-      end
-    end
-
-    opts.parse!(args)
-    options
-  end
-end
-
-def e(s)
-  return $zero+" error: "+s
-end
-
-def nopaste(nick, desc, text, lang = "Plain Text")
-  cxn = Net::HTTP::Proxy($proxy.host, $proxy.port, $proxy_user, $proxy_pass
-                        ).start($url.host, $url.port) { |cxn|
-    response = cxn.request_post($url.path, 
-      [ "cvt_tabs=No",
-        "lang=#{CGI::escape(lang)}",
-        "nick=#{CGI::escape(nick)}",
-        "desc=#{CGI::escape(desc)}",
-        "text=#{CGI::escape(text)}" ].join('&'),
-      { 'Content-Type' => 'application/x-www-form-urlencoded' })
-
-    if $options.debug
-      STDERR.puts response.inspect
-      response.each_header {|k,v| STDERR.printf "%s: %s\n", k, v}
-      STDERR.puts response.body
-    end
-
-    case response
-    when Net::HTTPRedirection
-      if response['location'] =~ /toofast.html/
-        return e("rafb.net says you're pasting too fast.  Try again in 10 seconds")
-      else
-        u = $url.merge(response['location'])
-        u.path = u.path.sub(/html$/, 'txt') if $options.txturl
-        return u
-      end
-    when Net::HTTPSuccess
-      # strange
-      return e("rafb.net sent an unexpected HTML response")
+    if [[ $# -gt 0 ]]; then
+        declare f u
+        for f; do
+            if [[ ! -r $f ]]; then
+                echo "nopaste: can't read $f" >&2
+                exit 1
+            fi
+            u=$(docurl --form-string "code2=$(<$f)")
+            urls+=( "$u" )
+            opt_parent=$(pid "$u")
+        done
     else
-      return e("rafb.net says #{response.code} #{response.message}")
-    end
-  }
-end
+        declare buf
+        if $opt_xcut; then
+            buf=$(get_x_clipboard) || exit 1
+        else
+            read -d '' buf
+            [[ -n $buf ]] || exit 1
+        fi
+        urls=( "$(docurl --form-string "code2=$buf")" )
+    fi
 
-$proxy = URI.parse(ENV['http_proxy'] || '')
-$proxy_user, $proxy_pass = nil, nil
-$proxy_user, $proxy_pass = $proxy.userinfo.split(/:/) if $proxy.userinfo
-$url = URI.parse("http://www.rafb.net/paste/paste.php")
-$version = '$Revision: 2835 $'.split(' ')[1]
-$zero = $0.sub(/.*\//, '')
-$options = CmdLine.parse(ARGV)
-urls = []
+    put_x_clipboard <<<"${urls[*]}"
+    printf "%s\n" "${urls[@]}"
+}
 
-if $options.desc.to_s.empty?
-  if $options.xcut
-    $options.desc = 'xcut'
-  elsif ARGV.empty?
-    $options.desc = 'stdin'
-  else
-    $options.desc = ARGV[0]
-  end
-end
+docurl() {
+    declare u
+    u=$(curl --silent --show-error -o /dev/null -w "%{redirect_url}\n" \
+        --form-string "poster=$opt_nick" --form-string "format=$opt_language" \
+        --form-string "expiry=$expire" \
+        ${opt_parent:+--form-string "parent_pid=$opt_parent"} \
+        -F "paste=Send" -F "remember=0" "$@" "$pastebin_url") || exit 1
+    if [[ -n $opt_parent ]] && $opt_diff; then
+        u="$pastebin_url?diff=$(pid "$u")"
+    elif $opt_download; then
+        u="$pastebin_url?dl=$(pid "$u")"
+    fi
+    echo "$u"
+}
 
-if $options.nick.to_s.empty?
-  $options.nick = ENV['USER'] || 'unknown'
-end
+pid() {
+    echo "${1##*[/=]}"
+}
 
-begin
-  if $options.xcut
-    buf = %x{xclip -o 2>/dev/null || xcut -p 2>/dev/null}
-    urls << nopaste($options.nick, $options.desc, buf, $options.lang)
-  elsif ARGV.empty?
-    urls << nopaste($options.nick, $options.desc, gets(nil), $options.lang)
-  end
+get_x_clipboard() {
+    if type -P xclip &>/dev/null; then
+        xclip -o
+    elif type -P xcut &>/dev/null; then
+        xcut -p
+    else
+        echo "nopaste: xclip or xcut required for --xcut" >&2
+        return 1
+    fi
+}
 
-  urls << nopaste($options.nick, $options.desc, gets(nil), $options.lang) until ARGV.empty?
-  begin
-    IO.popen("xclip 2>/dev/null", "w") {|p| p.print urls.map {|u| u.to_s}.join(' ') }
-  rescue Errno::EPIPE
-    begin
-      IO.popen("xcut 2>/dev/null", "w") {|p| p.print urls.map {|u| u.to_s}.join(' ') }
-    rescue Errno::EPIPE
-    end
-  end
+put_x_clipboard() {
+    xclip 2>/dev/null || xcut 2>/dev/null
+}
 
-rescue
-  puts urls # whatever we've accumulated already
-  puts e("something bad happened, stack trace follows")
-  raise
-end
+opt_expire:() {
+  case $1 in
+    d*) expire=d ;;     # day
+    [fn]*) expire=f ;;  # forever/never
+    *) expire=m ;;      # month
+  esac
+}
+opt_help() { usage; exit; }
+opt_version() { echo "nopaste $nopaste_version"; exit; }
 
-puts urls
-exit 1 if urls.join("\n") =~ /^(?!http:)/
+usage() {
+    cat <<'EOT'
+    usage: nopaste [options] [files]
+
+    -e --expire    Set expiry d/m/f, defaults to forever
+    -l --language  Set language, defaults to text
+    -n --nick      Set nick (honors PASTEBIN_USER)
+    -p --parent    Set parent paste id, for diffs
+    -x --xcut      Paste from X selection (using xclip or xcut)
+
+    --diff         Return diff URL (with --parent or multiple)
+    --download     Return download URL
+
+    --help         Show this help
+    --version      Show version info
+EOT
+}
+
+#=============================================================================
+# simple bash command-line processing
+#
+# (c) Copyright 2008 Aron Griffis <agriffis n01se.net>
+# Released under the GNU GPL v2
+#=============================================================================
+
+parse_cmdline() {
+    # extract long options from variable declarations
+    declare getopt_long=$(set | \
+        sed '/^opt_/!d; s/^opt_//; s/_/-/g;
+            s/\(.*\)=false$/\1 no-\1/;
+            s/\(.*\)=true$/\1 no-\1/;
+            s/=.*/:/; s/()//;' | xargs | sed 's/ /,/g')
+
+    # augment the shortopts array with takes-a-value colon;
+    # for example f:file becomes f::file
+    declare shortopts=( "${shortopts[@]}" )
+    declare i x
+    for ((i=0; i<${#shortopts[@]}; i++)); do
+        x=${shortopts[i]}
+        if [[ ",$getopt_long," == *,"${x#?:}":,* ]]; then
+            shortopts[i]=${x/:/::}
+        fi
+    done
+    declare getopt_short=$(IFS=''; echo "${shortopts[*]%:*}")
+
+    declare args
+    args=$(getopt -o "$getopt_short" \
+        --long "$getopt_long" -n "$0" -- "$@") || return
+    eval set -- "$args"
+
+    declare opt var val
+    parsed_opts=()
+    while true; do
+        [[ $1 == -- ]] && { shift; break; }
+
+        # translate short options to long
+        if [[ $1 == -? ]]; then
+            opt=${1#-}
+            for x in "${shortopts[@]}"; do
+                if [[ $x == "$opt":* ]]; then
+                    opt=${x##*:}
+                    break
+                fi
+            done
+        else
+            opt=${1#--}
+        fi
+
+        # figure out $var and $val; shift positional params
+        var=opt_${opt//-/_}
+        case ",$getopt_long," in
+            # make sure to handle opt_no_something (--no-something) 
+            # which has a (silly) negation of --no-no-something
+            *",no-$opt,"*)
+                val=true
+                parsed_opts=( "${parsed_opts[@]}" "$1" )
+                shift ;;
+            *",$opt,"*)
+                if [[ $opt == no-* ]]; then
+                    var=${var/no_/}
+                    val=false
+                else
+                    val=true
+                fi
+                parsed_opts=( "${parsed_opts[@]}" "$1" )
+                shift ;;
+            *",$opt:,"*) 
+                val=$2
+                parsed_opts=( "${parsed_opts[@]}" "$1" "$2" )
+                shift 2 ;;
+            *)
+                echo "error processing $1: not in getopt_long?" >&2
+                return 1 ;;
+        esac
+
+        if [[ $(type -t "$var") == function ]]; then
+            $var
+        elif [[ $(type -t "$var:") == function ]]; then
+            $var: "$val"
+        elif is_array "$var"; then
+            eval "$var=( \"\${$var[@]}\" $(printf %q "$val") )"
+        elif is_var "$var"; then
+            eval "$var=\$val"
+        else
+            echo "error processing $var: no func/array/var?" >&2
+            return 1
+        fi
+    done
+
+    parsed_params=( "$@" )
+}
+
+getopt() {
+    declare cmd=${cmd:-${0##*/}}
+    if [[ $(command getopt --help 2>&1) == *--longoptions* ]]; then
+        command getopt "$@"
+    elif [[ $OSTYPE == darwin* ]]; then
+        if [[ ! -x /opt/local/bin/getopt ]]; then
+            echo "Error: $cmd requires GNU getopt" >&2
+            echo "Please install from http://getopt.darwinports.com/" >&2
+            exit 1
+        fi
+        /opt/local/bin/getopt "$@"
+    else
+        echo "Error: $cmd requires GNU getopt" >&2
+        exit 1
+    fi
+}
+
+is_var() {
+    declare -p "$1" &>/dev/null
+}
+
+is_array() {
+    set -- $(declare -p "$1" 2>/dev/null)
+    [[ $2 == -*a* ]]
+}
+
+main "$@"
